# Generated by Django 5.2 on 2025-04-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_working',
        ),
    ]
