# Generated by Django 5.2 on 2025-04-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dismiss', 'Увольнение'), ('vacation', 'Отпуск')], max_length=50, verbose_name='Тип приказа'),
        ),
    ]
