# Generated by Django 5.2 on 2025-04-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dismiss', 'Увольнение'), ('vacation', 'Отпуск'), ('hire', 'Прием на работу'), ('sickleave', 'Больничный')], max_length=50, verbose_name='Тип приказа'),
        ),
    ]
