# Generated by Django 5.2 on 2025-04-22 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sickleave',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Приказ'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Приказ'),
        ),
    ]
